---
name: Backend Checks

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'app/backend/**'
      - 'docker-compose.ci.yml'
      - '.github/workflows/backend-checks.yml'

jobs:
  build-api:
    uses: ./.github/workflows/build-container.yml
    with:
      service: API
      context: ./app/backend
      dockerfile: ./app/backend/Dockerfile
      image_name: store-front-api
      build_args: |
        DEV=true
    secrets:
      dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  lint:
    name: Lint API Code
    runs-on: ubuntu-24.04
    needs: [build-api]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Lint
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          IMAGE_TAG: ${{ needs.build-api.outputs.image_tag }}
        run: docker compose -f docker-compose.ci.yml run api ruff check .

  test-api:
    name: Test API
    runs-on: ubuntu-24.04
    needs: [build-api]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          IMAGE_TAG: ${{ needs.build-api.outputs.image_tag }}
        run: docker compose -f docker-compose.ci.yml run api pytest
