---
name: Application Checks

on: [push]

jobs:
  build-api:
    name: Build API Container
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USER }}/store-front-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/store-front-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/store-front-api:buildcache,mode=max
          build-args: |
            DEV=true

  build-frontend:
    name: Build Frontend Container
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USER }}/store-front-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/store-front-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/store-front-frontend:buildcache,mode=max
          build-args: |
            USER_ID=1000
            GROUP_ID=1000

  test-api:
    name: Test API
    runs-on: ubuntu-24.04
    needs: [build-api]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "IMAGE_TAG=${BRANCH_NAME}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Test
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        run: docker compose -f docker-compose.ci.yml run api pytest