---
name: Main Branch Merge

on:
  push:
    branches:
      - main

jobs:
  latest-backend:
    name: Build and Push Latest Backend
    uses: ./.github/workflows/build-container.yml
    with:
      is_latest: true
      service: api
      context: ./app/backend
      dockerfile: ./app/backend/Dockerfile
      repository_name: store-front
      build_args: |
        PRODUCTION=true
    secrets:
      dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  latest-frontend:
    name: Build and Push Latest Frontend
    uses: ./.github/workflows/build-container.yml
    with:
      is_latest: true
      service: frontend
      context: ./app/frontend
      dockerfile: ./app/frontend/Dockerfile
      repository_name: store-front
      build_args: |
        NODE_ENV=production
    secrets:
      dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}